# Generated by Django 4.2.16 on 2024-11-07 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0002_profile_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
