# Generated by Django 4.2 on 2023-11-17 04:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('Hasliked', django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(), size=None)),
            ],
        ),
    ]
