# Generated by Django 4.2 on 2023-11-17 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.CharField(default='Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum debitis reprehenderit et blanditiis quam ex molestiae culpa, eius dolorem voluptate? Incidunt nostrum natus ut. Dicta, voluptas quam labore dolorum eius cum quisquam qui numquam quae?', max_length=500),
        ),
    ]
