# Generated by Django 4.2.16 on 2024-11-07 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_remove_pd_project_like_users_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowerdata',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
