# Generated by Django 4.2.16 on 2024-11-08 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_flowerdata_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowerdata',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
